/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WindowsUtils */

#ifndef _Included_WindowsUtils
#define _Included_WindowsUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WindowsUtils
 * Method:    flash
 * Signature: (Ljava/awt/Component;Z)V
 */
JNIEXPORT void JNICALL Java_WindowsUtils_flash
  (JNIEnv *, jobject, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
