/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class win32_WindowsUtils */

#ifndef _Included_win32_WindowsUtils
#define _Included_win32_WindowsUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     win32_WindowsUtils
 * Method:    flash
 * Signature: (Ljava/awt/Component;Z)V
 */
JNIEXPORT void JNICALL Java_win32_WindowsUtils_flash
  (JNIEnv *, jobject, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
